### PR TITLE
Adding a study in Unit 3

### PR DESCRIPTION
**Pull request by zihan21206**
Adding a between-subjects study in Unit 3, which compares the effectiveness of providing the most common student solution as Parsons problems when writing code, versus not providing the Parsons problems.

@barbarer

### CODE REVIEW

**Comment by barbarer** [comment]
I support this pull request.  It is for an experiment that we would like to run.

**Comment by bnmnetp** [comment]
This is really @bhoffman0 's call, adding a whole new section in the middle of the semester always seems risky to me.

**Comment by barbarer** [comment]
It is being added at the end of the unit.

Dr. Barbara Ericson
Associate Professor, School of Information
University of Michigan

**Comment by bhoffman0** [comment]
This is the wrong github repo. Could your student please open the PR on
https://github.com/bhoffman0/CSAwesome/?
Thanks,
Beryl

**Comment by barbarer** [comment]
I have told her.

Dr. Barbara Ericson
Associate Professor, School of Information
University of Michigan

**Pull request closed without merging**
